version: '3.5'
services:
  sql:
    image: mysql:5.7
    volumes:
      - ./data/sql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/xx-local.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bacula-db
      MYSQL_USER: bacula-user
      MYSQL_PASSWORD: bacula-password
  director:
    image: glorpen/bacula/director:latest
    depends_on:
      - storage
      - client-1
      - sql
    volumes:
      - ./bacula-dir.conf:/opt/bacula/etc/bacula-dir.conf
  storage:
    image: glorpen/bacula/storage:latest
    volumes:
      - ./bacula-sd.conf:/opt/bacula/etc/bacula-sd.conf
      - ./data/backup:/srv/backup
  client-1:
    image: glorpen/bacula/client:latest
    volumes:
      - ./bacula-fd.conf:/opt/bacula/etc/bacula-fd.conf
  console:
    image: glorpen/bacula/console:latest
    depends_on:
      - director
    volumes:
      - ./bconsole.conf:/opt/bacula/etc/bconsole.conf
  client-mysql:
    image: glorpen/bacula/client-mysql:latest
    environment:
      MYSQL_PASSWORD: root
      MYSQL_HOST: sql
    volumes:
      - ./bacula-fd-mysql.conf:/opt/bacula/etc/bacula-fd.conf
      - ./data/sql:/var/lib/mysql

#db_user=bacula-user db_name=bacula-db db_password=bacula-password /etc/bacula/scripts/make_mysql_tables -uroot -proot
